Framework '4.0x86'

properties {
    $base_dir = resolve-path .
    $source_dir = "$base_dir\src"
    $build_dir = "$base_dir\build"
    $dist_dir = "$base_dir\dist"
    $tools_dir = "$base_dir\tools"
    $node_dir = "$base_dir\node"
    $node_exe = "$node_dir\node.exe"
    $npm_cli = "$node_dir\npm\bin\npm-cli.js"
    $global:config = "Debug"
	$buildNumber = if ( $env:APPVEYOR_BUILD_NUMBER  -ne $NULL) { $env:APPVEYOR_BUILD_NUMBER  } else { "9999" }
	$version = "0.0.0.$buildNumber"
    $nuget = "$tools_dir\NuGet\NuGet.exe"
}

task default -depends local
task local -depends compile, test
task full -depends local, dist
task ci -depends clean, release, commonAssemblyInfo, local, installNode, dist

task clean {
    delete_directory $build_dir
    delete_directory $dist_dir
}

task release {
    $global:config = "Release"
}

task compile -depends clean {
    create_directory $build_dir
    exec { & $nuget restore "$source_dir\Skimur.sln" }
	exec { msbuild /t:Clean /t:Build /p:Configuration=$config /p:VisualStudioVersion=14.0 /p:Platform='Any CPU' /p:OutputPath="$build_dir" /p:CI=true $source_dir\Skimur.sln }
}

task commonAssemblyInfo {
    $commit = if ($env:BUILD_VCS_NUMBER -ne $NULL) { $env:BUILD_VCS_NUMBER } else { git log -1 --pretty=format:%H }
    create-globalAssemblyInfo "$commit" "$source_dir\GlobalAssemblyInfo.cs"
}

task installNode {
    delete_directory $node_dir
    create_directory $node_dir
    
    $client = new-object System.Net.WebClient
    $client.DownloadFile("https://nodejs.org/download/release/v4.1.1/win-x64/node.exe", "$node_dir\node.exe")

    create_directory "$node_dir\npm"
    git clone -b "v3.3.4" --single-branch https://github.com/npm/npm.git "$node_dir\npm"

    Set-Location -Path "$node_dir"
    exec { & $node_exe npm install less  }
    exec { & $node_exe npm install less-plugin-clean-css  }
    Set-Location -Path "$base_dir"
}

task test {
	# todo
}

task dist {
	create_directory $dist_dir
	copy_files "$build_dir\_PublishedWebsites\Skimur.Web.Public" "$dist_dir\Web"
    copy_files "$build_dir\Subs.Worker.Cons" "$dist_dir\Subs.Worker.Cons"

    create_directory "$dist_dir\static"
    Set-Location -Path "$node_dir"
    exec { & "$node_dir\lessc" --clean-css="--s0" "$build_dir\_PublishedWebsites\Skimur.Web.Public\Content\site.less" "$dist_dir\static\site.css" }
    exec { & $node_exe npm install less-plugin-clean-css  }
    Set-Location -Path "$base_dir"
}

function global:create-globalAssemblyInfo($commit, $filename)
{
	$date = Get-Date
    "using System;
using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute(""$version"")]
[assembly: AssemblyFileVersionAttribute(""$version"")]
[assembly: AssemblyCopyrightAttribute(""Copyright Skimur " + $date.Year + """)]
[assembly: AssemblyProductAttribute(""Skimur"")]
[assembly: AssemblyTrademarkAttribute(""Skimur"")]
[assembly: AssemblyCompanyAttribute("""")]
[assembly: AssemblyConfigurationAttribute(""$config"")]
[assembly: AssemblyInformationalVersionAttribute(""$config"")]"  | out-file $filename -encoding "ASCII"    
}

function global:copy_files($source, $destination, $regexFilter = $NULL) {

    create_directory $destination

	if($regexFilter -eq $null) {
		$regexFilter = ".*"
	}

    Get-ChildItem $source -Recurse -Exclude $exclude | Where-Object {$_.FullName -match $regexFilter} |  Copy-Item -Destination {Join-Path $destination $_.FullName.Substring($source.length)} 
}

function global:copy_file($source, $destination) {
    if(!(Test-Path $source)) {
        Write-Error "The file $source doesn't exist, so it can't be copied."
    }
    Copy-Item $source $destination
}


function global:create_directory($directory_name) {
    mkdir $directory_name  -ErrorAction SilentlyContinue  | out-null
}

function global:delete_directory($directory_name) {
    rd $directory_name -recurse -force  -ErrorAction SilentlyContinue | out-null
}