using System;
using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("0.0.0.9999")]
[assembly: AssemblyFileVersionAttribute("0.0.0.9999")]
[assembly: AssemblyCopyrightAttribute("Copyright Skimur 2015")]
[assembly: AssemblyProductAttribute("Skimur")]
[assembly: AssemblyTrademarkAttribute("Skimur")]
[assembly: AssemblyCompanyAttribute("")]
[assembly: AssemblyConfigurationAttribute("Release")]
[assembly: AssemblyInformationalVersionAttribute("Release")]
