using System.Reflection;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
[assembly: AssemblyVersion("0.0.0.2")]
[assembly: AssemblyFileVersion("0.0.0.2")]
[assembly: AssemblyCopyright("Copyright Skimur 115")]
[assembly: AssemblyProduct("Skimur")]
[assembly: AssemblyTrademark("Skimur")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyInformationalVersion("Release")]